apiVersion: v1
kind: Service
metadata:
  name: els-master-svc
spec:
  selector:
    app: elasticsearch-master
  clusterIP: None
  ports:
    - port: 9200
      name: api
    - port: 9300
      name: nodes
---
apiVersion: v1
kind: Service
metadata:
  name: els-data-svc
spec:
  selector:
    app: elasticsearch-data
  clusterIP: None
  ports:
    - port: 9200
      name: api
    - port: 9300
      name: nodes
