apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv0
spec:
  storageClassName: manual
  capacity:
    storage: 1000Mi
  accessModes:
    - "ReadWriteOnce"
  nfs:
    server: 192.168.1.8 
    path: "/srv/nfs/kubedata/pv0"
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-nfs-pv1
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1000Mi
#   accessModes:
#     - "ReadWriteOnce"
#   nfs:
#     server: 192.168.1.8 
#     path: "/srv/nfs/kubedata/pv1"
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-nfs-pv2
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1000Mi
#   accessModes:
#     - "ReadWriteOnce"
#   nfs:
#     server: 192.168.1.8 
#     path: "/srv/nfs/kubedata/pv2"